name: Release IntelliJ IDEA Plugin
on:
  push:
    tags:
      - 'intellij/*'

jobs:
  build:
    name: intellij
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          persist-credentials: false

      - name: Setup Java 8 and Apache Maven
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Configure GIT
        run: |
          git config --global user.name "Gluon Bot"
          git config --global user.email "githubbot@gluonhq.com"

      - name: Publish to IntelliJ Marketplace
        run: |
          chmod +x intellij/gradlew
          ./gradlew clean publishPlugin -p intellij

      - name: Commit next development version
        if: steps.deploy.outputs.exit_code == 0
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          TAG_VERSION=$(echo $TAG | cut -d/ -f2)
          NEXT_VERSION=${TAG_VERSION%.*}.$((${TAG_VERSION##*.} + 1))
          echo "Update intellij version to next snapshot version"
          sed -i -z "0,/version=$TAG/s//version=$newVersion-SNAPSHOT/" intellij/gradle.properties
          git commit intellij/gradle.properties -m "Prepare development of $NEXT_VERSION"
          git push https://gluon-bot:$PAT@github.com/$GITHUB_REPOSITORY HEAD:master
        shell: bash
        env:
          PAT: ${{ secrets.PAT }}