name: Release Netbeans Plugin
on:
  push:
    tags:
      - 'netbeans/*'

jobs:
  build:
    name: netbeans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          persist-credentials: false

      - name: Setup Java 8 and Apache Maven
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure GIT
        run: |
          git config --global user.name "Gluon Bot"
          git config --global user.email "githubbot@gluonhq.com"

      - name: Publish to Maven Central
        id: deploy
        run: |
          mvn deploy -DskipTests=true -B -U -Prelease -f netbeans
          echo ::set-output name=exit_code::$?
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Commit next development version
        if: steps.deploy.outputs.exit_code == 0
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          TAG_VERSION=$(echo $TAG | cut -d/ -f2)
          NEXT_VERSION=${TAG_VERSION%.*}.$((${TAG_VERSION##*.} + 1))
          echo "Update netbeans version to next snapshot version"
          mvn versions:set -DnewVersion=$NEXT_VERSION-SNAPSHOT -DgenerateBackupPoms=false -f netbeans
          git commit netbeans/pom.xml -m "Prepare development of $NEXT_VERSION"
          git push https://gluon-bot:$PAT@github.com/$GITHUB_REPOSITORY HEAD:master
        shell: bash
        env:
          PAT: ${{ secrets.PAT }}